---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# statbank

<!-- badges: start -->
<!-- badges: end -->

The goal of statbank is to ...

## Installation

You can install the released version of statbank from [CRAN](https://CRAN.R-project.org) with:

```{r, eval=FALSE}
install.packages("statbank")
```

And the development version from [GitHub](https://github.com/) with:

```{r, eval=FALSE}
# install.packages("remotes")
remotes::install_github("akselthomsen/statbank")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(statbank)
## basic example code

x <- tbl_dst(table_id = "FOLK1B", lang = "en")

class(x)
```

```{r}
x
```

```{r}
x %>% head()
x %>% tail()
```

```{r}
x %>%
  sample_n(8) %>%
  show_query() %>%
  print() %>% 
  use_bulk_download()
```

```{r}
x %>% 
  use_names()
```

